### ISSUE TITLE
So what's the actual benchmarks improvement ?

### ISSUE THREAD

**Issue by rconnolly2** [ViveSoftware/ViveFoveatedRendering#1]
Hi
It would be nice to know the actual benchmarks improvement.
of eye foveated rendering vs non.

You could also add it to the mainpage.

Best regards
Robert

**Comment by kyo8568131** [comment]
Hi Robert,
The performance improvement is about 15%~25% in our test case compared with non-foveated rendering.
But it actually depends on the pixel shading load of your application. If the pixel shading load is your application's bottleneck, you would gain more performance improvement. And you could also adjust the shading rate and shading region for more aggressive result. 
Thanks.

**Comment by rconnolly2** [comment]
15-25% Isn't that much I have seen foveated rendering projects that get 2.8X - 3.2X speedups.
https://www.youtube.com/watch?v=VOpC-xEaB-Q
https://xiaoxumeng1993.wixsite.com/xiaoxumeng/kernel-foveated-rendering
https://github.com/xmeng525/KernelFoveatedRendering_Unity

**Comment by kyo8568131** [comment]
Hi Robert,
As previous reply, the performance improvement depends on the pixel shading load of your application. But in real case, there are many kinds of reason to make performance poor. It would help a lot if you could try both of them and feedback your thought.
Thanks.
